ProdutoWeb/Controllers/AdminController.cs
using ProdutoWeb.DAO;
using ProdutoWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProdutoWeb.Controllers
{
    public class AdminController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            HttpCookie cookie = Request.Cookies["UsuarioProjetoWeb"];
            if (cookie != null)
            {
                String Email = cookie["Email"].ToString();
                String Senha = cookie["Senha"].ToString();
                Usuario UsuarioLogin = new Usuario(Email,Senha);

                Usuario UsuarioLogado = new UsuarioDAO().Login(UsuarioLogin.EmailUsuario, UsuarioLogin.SenhaUsuario);

                if (UsuarioLogado != null)
                {
                    Session["UsuarioLogado"] = UsuarioLogado;
                    cookie.Expires = DateTime.Now.AddDays(360);
                    Response.AppendCookie(cookie);

                    return View("Login");
                } else
                {
                    return View();
                }

            } else
            {
                return View();
            }

        }

        [HttpPost]
        public ActionResult Login(Usuario UsuarioLogin)
        {

            UsuarioDAO UserDAO = new UsuarioDAO();
            Usuario UsuarioLogado = UserDAO.Login(UsuarioLogin.EmailUsuario, UsuarioLogin.SenhaUsuario);

            if (UsuarioLogado != null )
            {
                // Usuario Encontrado e Login efetuado com sucesso.

                // Adicionando o usuário na Sessão
                Session["UsuarioLogado"] = UsuarioLogado;

                // Criando um Cookie
                HttpCookie cookie = new HttpCookie("UsuarioProjetoWeb");
                cookie.Values.Add("Email", UsuarioLogin.EmailUsuario);
                cookie.Values.Add("Senha", UsuarioLogin.SenhaUsuario);
                cookie.Expires = DateTime.Now.AddDays(360);
                Response.AppendCookie(cookie);


                // Exibindo a Tela com Login
                return View();
            }

            // Falha no Login
            else
            {
                TempData["Mensagem"] = "Usuário ou Senha inválida.";
                return View("Index", UsuarioLogin);
            }
        }



        public ActionResult Logoff()
        {
            Session.Clear();

            HttpCookie cookie = Request.Cookies["UsuarioProjetoWeb"];
            cookie.Expires = DateTime.Now.AddDays(-1);
            Response.AppendCookie(cookie);

            return View("Index");
        }

    }
}

ProdutoWeb/Views/Admin/Index.cshtml
@model ProdutoWeb.Models.Usuario

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Small Business - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="@Url.Content("~/Content/small-business.css")" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Content("~/Admin/Index")">
                    <img src="http://placehold.it/150x50&text=Logo" alt="">
                </a>
            </div>
            
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">

        <!-- Call to Action Well -->
        <div class="row">
            <div class="col-lg-12">
                <div class="well">
                    @if (!ViewData.ModelState.IsValid)
                    {
                        @Html.ValidationSummary()
                    }
                    @TempData["Mensagem"]

                    <h2>Login</h2>


                    @using (Html.BeginForm("Login", "Admin", FormMethod.Post))
                    {
                        <div class="form-group">
                            <label class="control-label" for="nome">Usuário:</label>
                            @Html.TextBoxFor(model => model.EmailUsuario, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EmailUsuario)
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="email">Senha:</label>
                            @Html.PasswordFor(model => model.SenhaUsuario, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.SenhaUsuario)

                        </div>
                        <button type="submit" class="btn btn-primary btn-lg">Enviar</button>
                    }



                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <!-- Footer -->
       
        
         <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2016</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="@Url.Content("~/scripts/jquery.js")"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="@Url.Content("~/scripts/bootstrap.min.js")"></script>
</body>
</html>



ProdutoWeb/Views/Admin/Login.cshtml

@{
    Layout = "~/Views/LayoutAdmin.cshtml";
    ProdutoWeb.Models.Usuario usuario = (ProdutoWeb.Models.Usuario)HttpContext.Current.Session["UsuarioLogado"];

}

<div class="container">
    <hr>
    <!-- Call to Action Well -->
    <div class="row">
        <div class="col-lg-12">
            <div class="well text-center">
                Bem Vindo @usuario.NomeUsuario
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright © Your Website 2014</p>
            </div>
        </div>
    </footer>

</div>