ProdutoWeb/Models/Contato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProdutoWeb.Models
{

    [Table("NETCONTATO")]
    public class Contato
    {
        
        [Key]
        [Column("IDCONTATO")]
        public int IdContato { get; set; }


        [Column("NOMECONTATO")]
        [Display(Name = "Nome", Description = "Digite o nome")]
        [Required(ErrorMessage = "Nome obrigatório")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "O campo Nome deve possuir no mínimo 3 e no máximo 50 caracteres")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage = "Digite o nome sem números e caracteres especiais.")]
        public string Nome { get; set; }


        [Column("EMAIL")]
        [Required(ErrorMessage = "e-Mail obrigatório")]
        [EmailAddress]
        public string Email { get; set; }


        [Column("MENSAGEM")]
        [Display(Name = "Mensagem", Description = "Digite o texto da mensagem")]
        [Required(ErrorMessage = "Mensagem Obrigatória")]
        [StringLength(2048, MinimumLength = 3, ErrorMessage = "O campo Nome deve possuir no mínimo 3 e no máximo 2048 caracteres")]
        public string Mensagem { get; set; }


        [Column("IDTIPOCONTATO")]
        public int IdTipoContato { get; set; }


        public TipoContato TipoContato { get; set; }


    }
}

ProdutoWeb/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProdutoWeb.Models;
using ProdutoWeb.DAO;

namespace ProdutoWeb.Controllers
{
    public class ContatoController : Controller
    {

        [HttpGet]
        public ActionResult Index(Models.Contato Contato)
        {
            IList<TipoContato> ListaTipoContato = new TipoContatoDAO().ListarTodos();
            ViewBag.ListaTipoContato = ListaTipoContato;
            ModelState.Clear();
            return View(Contato);
        }

        [HttpPost]
        public ActionResult Gravar(Models.Contato Contato)
        {

            if (ModelState.IsValid)
            {
                new ContatoDAO().Inserir(Contato);
                Contato = new Contato();
                ModelState.Clear();
                TempData["Mensagem"] = "Contato recebido e armazenado em nosso banco de dados. Obrigado!";

            } else
            {
                // ENVIAR O USUÁRIO PARA TELA DE ERRO.
                TempData["Mensagem"] = "Não foi possível cadastrar as informações!";

            }

            IList<TipoContato> ListaTipoContato = new TipoContatoDAO().ListarTodos();
            ViewBag.ListaTipoContato = ListaTipoContato;
            return View("Index", Contato);

        }

    }
}

ProdutoWeb/Views/Contato/GravarErro.cshtml

@{
    ViewBag.Title = "GravarErro";
    Layout = "~/Views/LayoutPortal.cshtml";
}

<h2>Ocorreu um erro na gravação das informações de contato.</h2>


ProdutoWeb/Views/Contato/GravarSucesso.cshtml

@{
    ViewBag.Title = "GravarSucesso";
    Layout = "~/Views/LayoutPortal.cshtml";
}

<h2>Informações Gravadas com sucesso.</h2>


ProdutoWeb/Views/Contato/Index.cshtml
@model ProdutoWeb.Models.Contato

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/LayoutPortal.cshtml";
}

<!-- Page Content -->
<div class="container">
    <!-- Call to Action Well -->
    <div class="row">
        <div class="col-lg-12">
            <div class="well">
                @TempData["Mensagem"]
                @if (!ViewData.ModelState.IsValid )
                {
                   @Html.ValidationSummary()
                }
  
                <h2>Contato</h2>

                
                @using (Html.BeginForm("Gravar", "Contato", FormMethod.Post))
                {
                    <div class="form-group">
                        <label class="control-label" for="Nome">Nome:</label>
                        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Nome)
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="Email">e-Mail:</label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="TipoContato.IdTipoContato">Tipo Contato:</label>
                        @Html.DropDownListFor(model => model.IdTipoContato, new SelectList(ViewBag.ListaTipoContato, "IdTipoContato", "NomeTipoContato"), "Selecione", new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="Mensagem">Mensagem:</label>
                        @Html.TextAreaFor(model => model.Mensagem, new { @class = "form-control", @cols=100, @rows=10 } )
                        @Html.ValidationMessageFor(model => model.Mensagem)
                    </div>

                    
                    <a class="btn btn-default btn-lg" href="/">Cancelar</a>
                    <button type="submit" class="btn btn-primary btn-lg">Gravar</button>

                }

            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
