ProdutoWeb/Models/Produto.cs
using ProdutoWeb.Resources;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProdutoWeb.Models
{

    [Table("NETPRODUTO")]
    public class Produto
    {

        public Produto()
        {
            Imagens = new Collection<Imagem>();
        }


        [Key]
        [Column("IDPRODUTO")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdProduto { get; set; }

        [Column("NOMEPRODUTO")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "O campo Nome deve possuir no mínimo 3 e no máximo 50 caracteres")]
        [Display(Name = "Nome", ResourceType = typeof(ProdutoResource), Description = "Digite o nome")]
        [Required(ErrorMessageResourceName = "NomeProdutoRequerido", ErrorMessageResourceType = typeof(ProdutoResource))]
        public String NomeProduto { get; set; }

        [Column("DESCRICAOPRODUTO")]
        [Display(Name = "Descrição", Description = "Digite a descrição")]
        [Required(ErrorMessage = "Descrição é obrigatório")]
        [StringLength(200, MinimumLength = 3, ErrorMessage = "O campo Descrição deve possuir no mínimo 3 e no máximo 200 caracteres")]
        public String DescricaoProduto { get; set; }

        [Column("PRECOPRODUTO")]
        [Display(Name = "Preço", Description = "Digite o Preço")]
        [Required(ErrorMessage = "Preço é obrigatório")]
        [Range(0, Double.PositiveInfinity)]
        public double PrecoProduto { get; set; }


        [Column("CARACTERISTICASPRODUTO")]
        [Display(Name = "Características", Description = "Digite a(s) característica(s)")]
        [Required(ErrorMessage = "Características é obrigatório")]
        [StringLength(2000, MinimumLength = 3, ErrorMessage = "O campo Características deve possuir no mínimo 3 e no máximo 2000 caracteres")]
        public String CaracteristicasProduto { get; set; }

        [Column("IMAGEMPADRAO")]
        [Display(Name = "Imagem", Description = "Digite a url da imagem")]
        [StringLength(2000, MinimumLength = 3, ErrorMessage = "O campo Imagem deve possuir no mínimo 3 e no máximo 200 caracteres")]
        public String ImagemPadrao { get; set; }


        [Column("ATIVO")]
        public bool Ativo { get; set; }


        public virtual ICollection<Imagem> Imagens { get; set; }

    }
}

ProdutoWeb/Controllers/ProdutoController.cs
using ProdutoWeb.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProdutoWeb.Models;
using ProdutoWeb.Filter;

namespace ProdutoWeb.Controllers
{
    
    [AcessoFilter]
    public class ProdutoController : Controller
    {

        [HttpGet]
        public ActionResult Index()
        {
            ProdutoDAO ProdDAO = new ProdutoDAO();
            IList<Models.Produto> lista = ProdDAO.ListarTodos();
            return View(lista);
        }

       

        [HttpGet]
        public ActionResult Inserir()
        {
            ModelState.Clear();
            return View(new Produto());
        }



        [HttpPost]
        public ActionResult Inserir(Produto Prod)
        {
            bool sucesso = true;

            if ( ModelState.IsValid ) { 

                ProdutoDAO ProdDAO = new ProdutoDAO();

                // Consultando produto já Existente
                Produto ProdExistente = ProdDAO.ConsultarPorNome(Prod.NomeProduto);
                if ( 
                        ( ProdExistente == null ) || 
                        (! String.Equals(Prod.NomeProduto, ProdExistente.NomeProduto)) 
                    )
                {
                    // Produtos são diferentes
                    ProdDAO.Inserir(Prod);

                    // Colocando na Temp Data
                    TempData["mensagem"] = "Produto inserido com sucesso";
                    
                } else
                {
                    ModelState.AddModelError("", "Produto duplicado");
                    sucesso = false;
                }

            } else
            {
                sucesso = false;
            }


            // Tratando o Redirecionamento
            if (sucesso)
            {
                return RedirectToAction("Index");
            } else
            {
                return View();
            }


        } // Fim Inserir



        [HttpGet]
        public ActionResult Editar(int Id)
        {
            return View(new ProdutoDAO().ConsultarPorId(Id));
        }



        [HttpPost]
        public ActionResult Editar(Produto Prod)
        {
            bool sucesso = true;

            if (ModelState.IsValid)
            {

                ProdutoDAO ProdDAO = new ProdutoDAO();

                // Consultando produto já Existente
                Produto ProdExistente = ProdDAO.ConsultarPorNome(Prod.NomeProduto);
                if (!String.Equals(Prod.NomeProduto, ProdExistente.NomeProduto))
                {
                    // Produtos são diferentes
                    ProdDAO.Editar(Prod);

                    // Colocando na Temp Data
                    TempData["mensagem"] = "Produto editado com sucesso";

                }
                else
                {
                    ModelState.AddModelError("", "Produto duplicado");
                    sucesso = false;
                }

            }
            else
            {
                sucesso = false;
            }


            // Tratando o Redirecionamento
            if (sucesso)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }


        } // Fim Inserir



        [HttpGet]
        public ActionResult Consultar(int Id)
        {
            return View(new ProdutoDAO().ConsultarPorId(Id));
        }


        [HttpGet]
        public ActionResult Excluir(int Id)
        {
            new ProdutoDAO().Excluir(Id);
            TempData["mensagem"] = "Produto excluido com sucesso";
            return RedirectToAction("Index");
        }



    }
}

ProdutoWeb/Views/Produto/Consultar.cshtml
@model ProdutoWeb.Models.Produto

@{
    Layout = "~/Views/LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Inserir</title>
</head>
<body>

    <!-- Page Content -->
    <div class="container">
        <!-- Call to Action Well -->
        <div class="row">
            <div class="col-lg-12">
                <div class="well">

                    <h2>Produto</h2>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NomeProduto, htmlAttributes: new { @class = "control-label" })
                            @Html.DisplayFor(model => model.NomeProduto);
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Descrição:</label>
                            @Html.DisplayFor(model => model.DescricaoProduto)
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Preço:</label>
                            @Html.DisplayFor(model => model.PrecoProduto)
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Características:</label>
                            @Html.DisplayFor(model => model.CaracteristicasProduto)
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Imagem Padrão:</label>
                            @Html.DisplayFor(model => model.ImagemPadrao)
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Imagens</label>
                        </div>
                        <hr>

                        @Html.ActionLink("Voltar", "Index", new object { }, new { @class = "btn btn-default btn-lg" })
                        

                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>

</body>
</html>

ProdutoWeb/Views/Produto/Editar.cshtml
@model ProdutoWeb.Models.Produto

@{
    Layout = "~/Views/LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Inserir</title>
</head>
<body>

    <!-- Page Content -->
    <div class="container">
        <!-- Call to Action Well -->
        <div class="row">
            <div class="col-lg-12">
                <div class="well">

                    <h2>Produto</h2>

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @using (Html.BeginForm("Editar", "Produto", FormMethod.Post))
                    {
                        <!-- // HIDDEN IDPRODUTO -->
                        <!-- // HIDDEN IDPRODUTO -->
                        @Html.HiddenFor(model => model.IdProduto)
                        <!-- // HIDDEN IDPRODUTO -->
                        <!-- // HIDDEN IDPRODUTO -->

                        <div class="form-group">
                            @Html.LabelFor(model => model.NomeProduto, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.NomeProduto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NomeProduto, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Descrição:</label>
                            @Html.TextAreaFor(model => model.DescricaoProduto, new { @class = "form-control", @cols = 100, @rows = 2 })
                            @Html.ValidationMessageFor(model => model.DescricaoProduto, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Preço:</label>
                            @Html.EditorFor(model => model.PrecoProduto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PrecoProduto, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Características:</label>
                            @Html.TextAreaFor(model => model.CaracteristicasProduto, new { @class = "form-control", @cols = 100, @rows = 4 })
                            @Html.ValidationMessageFor(model => model.CaracteristicasProduto, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Imagem Padrão:</label>
                            @Html.EditorFor(model => model.ImagemPadrao, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ImagemPadrao, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Imagens</label>
                        </div>
                        <hr>

                        @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn btn-default btn-lg" })
                        <input type="submit" value="Editar" class="btn btn-primary btn-lg" />

                    }


                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>

</body>
</html>

ProdutoWeb/Views/Produto/Index.cshtml
@using ProdutoWeb.Helper;

@model IEnumerable<ProdutoWeb.Models.Produto>

@{
    Layout = "~/Views/LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    
    <!-- Page Content -->
    <div class="container">
        <!-- Heading Row -->
        <div class="row">

            <div class="col-md-12">
                <h1>Produtos</h1>

                <p class="toolbar">
                    @Html.ActionLink("Novo Produto", "Inserir", new object { }, new { @class = "create btn btn-default" } )
                    <br />
                    <span class="alert">@TempData["mensagem"]</span>
                </p>
                <table class="table table-striped" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th data-field="name">@Html.DisplayNameFor(model => model.NomeProduto)</th>
                            <th data-field="stargazers_count">Descrição</th>
                            <th data-field="forks_count">Preço</th>
                            <th data-field="description">Características</th>
                            <th class="actions" width="220">Ações</th>
                        </tr>
                    </thead>
                    <tbody>

                       @foreach (var item in Model)
                       {
                        <tr>
                            <td>@item.NomeProduto</td>
                            <td>
                                <a href="/ProdutoDetalhe/@item.IdProduto/@UrlFormat.UrlAmigavel(item.DescricaoProduto)">
                                    @Html.DisplayFor(modelItem => item.DescricaoProduto)
                                </a>
                            </td>
                            <td>@Html.DisplayFor(modelItem => item.PrecoProduto)</td>
                            <td>@Html.DisplayFor(modelItem => item.CaracteristicasProduto)</td>
                            <td class="actions">
                                @Html.ActionLink("Editar", "Editar", new { id = item.IdProduto }, new { @class = "btn btn-warning btn-xs" })
                                @Html.ActionLink("Excluir", "Excluir", new { id = item.IdProduto }, new { @class = "btn btn-danger btn-xs" })
                            </td>
                        </tr>
                       }

                    </tbody>
                </table>



            </div>
            <!-- /.col-md-4 -->
        </div>
        <!-- /.row -->


</body>
</html>

ProdutoWeb/Views/Produto/Inserir.cshtml
@model ProdutoWeb.Models.Produto

@{
    Layout = "~/Views/LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Inserir</title>
</head>
<body>

    <!-- Page Content -->
    <div class="container">
        <!-- Call to Action Well -->
        <div class="row">
            <div class="col-lg-12">
                <div class="well">

                    <h2>@ProdutoWeb.Resources.ProdutoResource.Produto</h2>

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @using (Html.BeginForm("Inserir", "Produto", FormMethod.Post))
                    {
                        <div class="form-group">
                            @Html.LabelFor(model => model.NomeProduto, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.NomeProduto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NomeProduto, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Descrição:</label>
                            @Html.TextAreaFor(model => model.DescricaoProduto, new { @class = "form-control", @cols = 100, @rows = 2 })
                            @Html.ValidationMessageFor(model => model.DescricaoProduto, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Preço:</label>
                            @Html.EditorFor(model => model.PrecoProduto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PrecoProduto, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Características:</label>
                            @Html.TextAreaFor(model => model.CaracteristicasProduto, new { @class = "form-control", @cols = 100, @rows = 4 })
                            @Html.ValidationMessageFor(model => model.CaracteristicasProduto, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Imagem Padrão:</label>
                            @Html.EditorFor(model => model.ImagemPadrao, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ImagemPadrao, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="mesnagem">Imagens</label>
                        </div>
                        <hr>

                        @Html.ActionLink("Cancelar", "Index", new object { }, new { @class = "btn btn-default btn-lg" })

                        <input id="botaoInserir" type="button" value="Inserir" class="btn btn-primary btn-lg" />

                    }


                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>


        <script type="text/javascript">


            $(document).ready(function () {

                $("#botaoInserir").on('click', function (event) {

                    $.get("http://localhost:8885/", function (data, status) {
                        alert("Data: " + data + "\nStatus: " + status);
                    });

                });

            });



            /*
            $(document).ready(function () {

                $('#botaoInserir').on('click', function (event) {

                    if ($("#NomeProduto").val() == "") {
                        alert("Digite o nome");
                        $("#NomeProduto").focus();
                        $("#NomeProduto").css('background-color', 'red');
                        return;
                    } else {
                        $("#NomeProduto").css('background-color', 'white');
                        return;
                    }

                    $("form").eq(0).submit();

                });

            });
            */


           /*
            function inserir() {
           
                if (document.getElementById("NomeProduto").value == "") {
                    alert("Digite o nome");
                    document.getElementById("NomeProduto").focus();
                    document.getElementById("NomeProduto").style.background = 'red';
                    return;
                } else {
                    document.getElementById("NomeProduto").style.background = 'white';
                }

                if (document.getElementById("DescricaoProduto").value == "") {
                    alert("Digite a descrição");
                    document.getElementById("DescricaoProduto").focus();
                    return;
                }

                document.getElementsByTagName('form')[0].submit();
            
            }
             */
        </script>
</body>
</html>