ProdutoWeb/Controllers/ContatoAdminController.cs
using ProdutoWeb.DAO;
using ProdutoWeb.Models;
using System.Web.Mvc;

namespace ProdutoWeb.Controllers
{
    public class ContatoAdminController : Controller
    {
        [HttpGet]
        public ActionResult Index()  
        {
            return View();
        }


        [HttpPost]
        public ActionResult Index(Contato ContatoDigitado)
        {
           
            ViewBag.ListaContatoPesquisados =
                new ContatoDAO()
                    .Filtrar(
                        ContatoDigitado.Email,
                        ContatoDigitado.Nome);

            return View();
        }
    }
}

ProdutoWeb/Views/ContatoAdmin/Index.cshtml
@model ProdutoWeb.Models.Contato

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/LayoutAdmin.cshtml";
}

<div class="container">
    <!-- Heading Row -->
    <div class="row">

        <div class="col-md-12">
            <h1>Contatos - Lead</h1>


            <div class="well">
                <h3>Filtros</h3>

                @using (Html.BeginForm("Index", "ContatoAdmin", FormMethod.Post, new { @class = "form-inline" }))
                {
                    <div class="form-group">
                        <label class="control-label" for="nome">Nome:</label>
                        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="email">e-Mail:</label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                    </div>


                    <button type="submit" class="btn btn-primary btn-lg">Filtrar</button>
                }

            </div>


            @if ((ViewBag.ListaContatoPesquisados != null) && (ViewBag.ListaContatoPesquisados.Count > 0))
            {
                <table class="table table-striped" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th data-field="name">Nome</th>
                            <th data-field="Descricao">eMail</th>
                            <th class="actions" width="220">Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.ListaContatoPesquisados)
                        {
                            <tr>
                                <td>@item.Nome</td>
                                <td>@item.Email</td>
                                <td class="actions">
                                    <a class="btn btn-success btn-xs" href="javascript:alert('Em construção');">Visualizar</a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            }
            else
            {
                <p>Nenhum contato encontrado</p>
            }





        </div>
        <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->
